#!/bin/bash

archivo="/sys/devices/platform/msi-ec/webcam"

# Lee el valor actual del archivo
estado_actual=$(cat "$archivo")

# Cambia el estado de 'on' a 'off' o viceversa
if [ "$estado_actual" == 'on' ]; then
    nuevo_estado='off'
else
    nuevo_estado='on'
fi

# Escribe el nuevo estado en el archivo
echo "$nuevo_estado" > "$archivo"
notify-send "Operación completada" "Se ha cambiado la cámara modo a $nuevo_estado"

